# Generated by Django 4.2.13 on 2024-09-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URLMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.CharField(max_length=2048, unique=True)),
                ("short_url", models.CharField(max_length=20, unique=True)),
                ("expiration_date", models.DateTimeField()),
            ],
        ),
    ]
